#!/bin/bash
# Usage: ./pipeline_clembench.sh
# Preparation: ./setup.sh
echo
echo "==================================================="
echo "PIPELINE: Starting"
echo "==================================================="
echo
game_runs=(
  "codenames Mistral-7B-Instruct-v0.1"
#   "codenames llama3.1-8B-sft-e1-DFINAL"
# "adventuregame llama3.1-8B-sft-e1-DFINAL"
# "guesswhat llama3.1-8B-sft-e1-DFINAL"
# "matchit_ascii llama3.1-8B-sft-e1-DFINAL"
# "text_map_basic llama3.1-8B-sft-e1-DFINAL"
# "text_map_graph llama3.1-8B-sft-e1-DFINAL"
# "text_map_specific_room llama3.1-8B-sft-e1-DFINAL"
# "referencegame llama3.1-8B-sft-e1-DFINAL"
# "imagegame llama3.1-8B-sft-e1-DFINAL"
# "privateshared llama3.1-8B-sft-e1-DFINAL"
# "wordle_withclue llama3.1-8B-sft-e1-DFINAL"
# "taboo llama3.1-8B-sft-e1-DFINAL"
# "wordle_withcritic llama3.1-8B-sft-e1-DFINAL"

# "codenames Unsloth-meta-llama-3.1-4bit-plain"
# "adventuregame Unsloth-meta-llama-3.1-4bit-plain"
# "guesswhat Unsloth-meta-llama-3.1-4bit-plain"
# "matchit_ascii Unsloth-meta-llama-3.1-4bit-plain"
# "text_map_basic Unsloth-meta-llama-3.1-4bit-plain"
# "text_map_graph Unsloth-meta-llama-3.1-4bit-plain"
# "text_map_specific_room Unsloth-meta-llama-3.1-4bit-plain"
# "referencegame Unsloth-meta-llama-3.1-4bit-plain"
# "imagegame Unsloth-meta-llama-3.1-4bit-plain"
# "privateshared Unsloth-meta-llama-3.1-4bit-plain"
# "wordle_withclue Unsloth-meta-llama-3.1-4bit-plain"
# "taboo Unsloth-meta-llama-3.1-4bit-plain"
# "wordle_withcritic Unsloth-meta-llama-3.1-4bit-plain"

# "codenames qwen-coder-32B-sft-e1-DFINAL"
# "adventuregame qwen-coder-32B-sft-e1-DFINAL"
# "guesswhat qwen-coder-32B-sft-e1-DFINAL"
# "matchit_ascii qwen-coder-32B-sft-e1-DFINAL"
# "text_map_basic qwen-coder-32B-sft-e1-DFINAL"
# "text_map_graph qwen-coder-32B-sft-e1-DFINAL"
# "text_map_specific_room qwen-coder-32B-sft-e1-DFINAL"
# "referencegame qwen-coder-32B-sft-e1-DFINAL"
# "imagegame qwen-coder-32B-sft-e1-DFINAL"
# "privateshared qwen-coder-32B-sft-e1-DFINAL"
# "wordle_withclue qwen-coder-32B-sft-e1-DFINAL"
# "taboo qwen-coder-32B-sft-e1-DFINAL"
# "wordle_withcritic qwen-coder-32B-sft-e1-DFINAL"

# "codenames Unsloth-Qwen2.5-Coder-32B-bnb-4bit"
# "adventuregame Unsloth-Qwen2.5-Coder-32B-bnb-4bit"
# "guesswhat Unsloth-Qwen2.5-Coder-32B-bnb-4bit"
# "matchit_ascii Unsloth-Qwen2.5-Coder-32B-bnb-4bit"
# "text_map_basic Unsloth-Qwen2.5-Coder-32B-bnb-4bit"
# "text_map_graph Unsloth-Qwen2.5-Coder-32B-bnb-4bit"
# "text_map_specific_room Unsloth-Qwen2.5-Coder-32B-bnb-4bit"
# "referencegame Unsloth-Qwen2.5-Coder-32B-bnb-4bit"
# "imagegame Unsloth-Qwen2.5-Coder-32B-bnb-4bit"
# "privateshared Unsloth-Qwen2.5-Coder-32B-bnb-4bit"
# "wordle_withclue Unsloth-Qwen2.5-Coder-32B-bnb-4bit"
# "taboo Unsloth-Qwen2.5-Coder-32B-bnb-4bit"
# "wordle_withcritic Unsloth-Qwen2.5-Coder-32B-bnb-4bit"

# "codenames llama3.1-70B-sft-e1-DFINAL"
# "adventuregame llama3.1-70B-sft-e1-DFINAL"
# "guesswhat llama3.1-70B-sft-e1-DFINAL"
# "matchit_ascii llama3.1-70B-sft-e1-DFINAL"
# "text_map_basic llama3.1-70B-sft-e1-DFINAL"
# "text_map_graph llama3.1-70B-sft-e1-DFINAL"
# "text_map_specific_room llama3.1-70B-sft-e1-DFINAL"
# "referencegame llama3.1-70B-sft-e1-DFINAL"
# "imagegame llama3.1-70B-sft-e1-DFINAL"
# "privateshared llama3.1-70B-sft-e1-DFINAL"
# "wordle_withclue llama3.1-70B-sft-e1-DFINAL"
# "taboo llama3.1-70B-sft-e1-DFINAL"
# "wordle_withcritic llama3.1-70B-sft-e1-DFINAL"

# "codenames Unsloth-meta-llama-3.1-70B-bnb-4bit"
# "adventuregame Unsloth-meta-llama-3.1-70B-bnb-4bit"
# "guesswhat Unsloth-meta-llama-3.1-70B-bnb-4bit"
# "matchit_ascii Unsloth-meta-llama-3.1-70B-bnb-4bit"
# "text_map_basic Unsloth-meta-llama-3.1-70B-bnb-4bit"
# "text_map_graph Unsloth-meta-llama-3.1-70B-bnb-4bit"
# "text_map_specific_room Unsloth-meta-llama-3.1-70B-bnb-4bit"
# "referencegame Unsloth-meta-llama-3.1-70B-bnb-4bit"
# "imagegame Unsloth-meta-llama-3.1-70B-bnb-4bit"
# "privateshared Unsloth-meta-llama-3.1-70B-bnb-4bit"
# "wordle_withclue Unsloth-meta-llama-3.1-70B-bnb-4bit"
# "taboo Unsloth-meta-llama-3.1-70B-bnb-4bit"
# "wordle_withcritic Unsloth-meta-llama-3.1-70B-bnb-4bit"

)
total_runs=${#game_runs[@]}
echo "Number of benchmark runs: $total_runs"
current_runs=1
for run_args in "${game_runs[@]}"; do
  echo "Run $current_runs of $total_runs: $run_args"
  bash -c "./run.sh ${run_args}"
  ((current_runs++))
done
echo "==================================================="
echo "PIPELINE: Finished"
echo "==================================================="